/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Tue, Nov 12, 2019                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

#include "iodefine.h"
#include "hwsetup.h"

void stb_setup(void)
{
    STB.CR4.BIT._AD0 = 0;
    STB.CR4.BIT._AD1 = 0;
    STB.CR4.BIT._MTU2 = 0;
    STB.CR4.BIT._CMT = 0;
}

void clock_setup(void)
{
    CPG.FRQCR.BIT.IFC = 1;  // Iφ  = 50 [MHz]
    CPG.FRQCR.BIT.BFC = 3;  // Bφ  = 25 [MHz]
    CPG.FRQCR.BIT._PFC = 3; // Pφ  = 25 [MHz]
    CPG.FRQCR.BIT.MPFC = 3; // MPφ = 25 [MHz]
}

void setup_adconverter(void)
{
    AD0.ADCSR.BIT.ADM = 1;  // 4チャネルスキャンモード
    AD0.ADCSR.BIT.CKSL = 3; // クロック: Pφ/1 = 25 [MHz] = 40 [ns/count]
    AD0.ADCSR.BIT.STC = 1;  // 64ステート
    AD1.ADCSR.BIT.ADM = 1;  // 4チャネルスキャンモード
    AD1.ADCSR.BIT.CKSL = 3; // クロック: Pφ/1 = 25 [MHz] = 40 [ns/count]
    AD1.ADCSR.BIT.STC = 1;  // 64ステート
}

void io_setup(void)
{
    /***************************************
     * ポート A IO 設定                      *
     ***************************************/
    PFC.PAIORL.BIT.B0 = 0;  // F/B
    PFC.PAIORL.BIT.B1 = 0;  // BST
    PFC.PAIORL.BIT.B2 = 0;  // PBRK
    PFC.PAIORL.BIT.B3 = 0;  // RX
    PFC.PAIORL.BIT.B4 = 1;  // TX
    PFC.PAIORL.BIT.B5 = 0;  // RES0
    PFC.PAIORL.BIT.B6 = 0;  // RES1
    PFC.PAIORL.BIT.B7 = 0;  // RES2
    PFC.PAIORL.BIT.B8 = 0;  // RES3
    PFC.PAIORL.BIT.B9 = 0;  // RES4
    PFC.PAIORL.BIT.B10 = 0; // RES5
    PFC.PAIORL.BIT.B11 = 0; // RES6
    PFC.PAIORL.BIT.B12 = 0; // RES7
    PFC.PAIORL.BIT.B13 = 0; // RES8
    PFC.PAIORL.BIT.B14 = 0; // RES9
    PFC.PAIORL.BIT.B15 = 0; // RESERR

    PFC.PACRL1.BIT.PA0MD = 0;  // PA0 I/O
    PFC.PACRL1.BIT.PA1MD = 0;  // PA1 I/O
    PFC.PACRL1.BIT.PA2MD = 0;  // PA2 I/O
    PFC.PACRL1.BIT.PA3MD = 1;  // SCI RX
    PFC.PACRL2.BIT.PA4MD = 1;  // SCI TX
    PFC.PACRL2.BIT.PA5MD = 0;  // PA5 I/O
    PFC.PACRL2.BIT.PA6MD = 0;  // PA6 I/O
    PFC.PACRL2.BIT.PA7MD = 0;  // PA7 I/O
    PFC.PACRL3.BIT.PA8MD = 0;  // PA8 I/O
    PFC.PACRL3.BIT.PA9MD = 0;  // PA9 I/O
    PFC.PACRL3.BIT.PA10MD = 0; // PA10 I/O
    PFC.PACRL3.BIT.PA11MD = 0; // PA11 I/O
    PFC.PACRL4.BIT.PA12MD = 0; // PA12 I/O
    PFC.PACRL4.BIT.PA13MD = 0; // PA13 I/O
    PFC.PACRL4.BIT.PA14MD = 0; // PA14 I/O
    PFC.PACRL4.BIT.PA15MD = 0; // PA15 I/O

    /***************************************
     * ポート B IO 設定                      *
     ***************************************/
    PFC.PBIORL.BIT.B1 = 1;  // SPI CS
    PFC.PBIORL.BIT.B2 = 1;  // SPI SCK
    PFC.PBIORL.BIT.B3 = 1;  // SPI SDA1
    PFC.PBIORL.BIT.B5 = 1;  // SPI SDA2
    PFC.PBIORH.BIT.B16 = 1; // MCP4922 LDAC-bar

    PFC.PBCRL1.BIT.PB1MD = 0;  // PB1 I/O
    PFC.PBCRL1.BIT.PB2MD = 0;  // PB2 I/O
    PFC.PBCRL1.BIT.PB3MD = 0;  // PB3 I/O
    PFC.PBCRL2.BIT.PB5MD = 0;  // PB5 I/O
    PFC.PBCRH1.BIT.PB16MD = 0; // PB16 I/O

    /***************************************
     * ポート E IO 設定                      *
     ***************************************/
    PFC.PEIORL.BIT.B0 = 1;  // FWDIDC
    PFC.PEIORL.BIT.B1 = 1;  // BKWIDC
    PFC.PEIORL.BIT.B2 = 1;  // ERRIDC
    PFC.PEIORL.BIT.B3 = 0;  // FBRK
    PFC.PEIORL.BIT.B4 = 0;  // DMS
    PFC.PEIORL.BIT.B5 = 1;  // NONE
    PFC.PEIORL.BIT.B6 = 0;  // PROTECT
    PFC.PEIORL.BIT.B7 = 1;  // NONE
    PFC.PEIORL.BIT.B8 = 1;  // PWMTGL
    PFC.PEIORL.BIT.B9 = 1;  // PWM U
    PFC.PEIORL.BIT.B10 = 1; // NONE
    PFC.PEIORL.BIT.B11 = 1; // PWM U'
    PFC.PEIORL.BIT.B12 = 1; // PWM V
    PFC.PEIORL.BIT.B13 = 1; // PWM W
    PFC.PEIORL.BIT.B14 = 1; // PWM V'
    PFC.PEIORL.BIT.B15 = 1; // PWM W'

    PFC.PECRL1.BIT.PE0MD = 0;  // PE0 I/O
    PFC.PECRL1.BIT.PE1MD = 0;  // PE1 I/O
    PFC.PECRL1.BIT.PE2MD = 0;  // PE2 I/O
    PFC.PECRL1.BIT.PE3MD = 0;  // PE3 I/O
    PFC.PECRL2.BIT.PE4MD = 0;  // PE4 I/O
    PFC.PECRL2.BIT.PE5MD = 0;  // PE5 I/O
    PFC.PECRL2.BIT.PE6MD = 0;  // PE6 I/O
    PFC.PECRL2.BIT.PE7MD = 0;  // PE7 I/O
    PFC.PECRL3.BIT.PE8MD = 1;  // TIOC3A (TOGGLE)
    PFC.PECRL3.BIT.PE9MD = 1;  // TIOC3B (U)
    PFC.PECRL3.BIT.PE10MD = 0; // PE10 I/O
    PFC.PECRL3.BIT.PE11MD = 1; // TIOC3D (U')
    PFC.PECRL4.BIT.PE12MD = 1; // TIOC4A (V)
    PFC.PECRL4.BIT.PE13MD = 1; // TIOC4B (W)
    PFC.PECRL4.BIT.PE14MD = 1; // TIOC4C (V')
    PFC.PECRL4.BIT.PE15MD = 1; // TIOC4D (W')
}
