/***********************************************************************/
/*                                                                     */
/*  FILE        :MotorDriver.c                                         */
/*  DATE        :Tue, Nov 12, 2019                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

/*
 *                                        PIN
 *                  CN1                                           CN2
 *  PE00 FWDIDC  | 01 02 |    PE01 BWDIDC  |    PA00   F/B     | 01 02 |  PA01    BST
 *  PE02 ERRIDC  | 03 04 |    PE03 FBRK    |    PA02   PBRK    | 01 02 |  PA03    RX
 *  PE04 DMS     | 05 06 |    PE05 NONE    |    PA04   TX      | 05 06 |  PA05    RES0
 *  PE06 PROTECT | 07 08 |    PE07 NONE    |    PA06   RES1    | 07 08 |  PA07    RES2
 *  PE08 PWMTGL  | 09 10 |    PE09 PWM_U   |    PA08   RES3    | 09 10 |  PA09    RES4
 *  PE10 NC      | 11 12 |    PE11 PWM_U'  |    PA10   RES5    | 11 12 |  PA11    RES6
 *  PE12 PWM_V   | 13 14 |    PE13 PWM_W   |    PA12   RES7    | 13 14 |  PA13    RES8
 *  PE14 PWM_V'  | 15 16 |    PE15 PWM_W'  |    PA14   RES9    | 15 16 |  PA15    RESERR
 *  PF00 I_U     | 17 18 |    PF01 I_V     |    PB01   NONE    | 17 18 |  PB02    NONE
 *  PF02 I_W     | 19 20 |    PF03 I_DC    |    PB03   NONE    | 19 20 |  PB05    NONE
 *  PF04 ACC1    | 21 22 |    PF05 ACC2    |    PB16   NONE    | 21 22 |  RES     NONE
 *  PF06 NONE    | 23 24 |    PF07 NONE    |    NMI    NONE    | 23 24 |  WDTOVF  NONE
 *  MD1  NONE    | 25 26 |    FWE  NONE    |    ASEMD0 NONE    | 25 26 |  FWE     NONE
 *  Vcc  NONE    | 27 28 |    Vcc  NONE    |    GND    NONE    | 27 28 |  GND     NONE
 * 
 *  ---------------------------------------------------------------------------------
 *     FWDIDC = 前進 インジケータ
 *     BWDIDC = 後退 インジケータ
 *     ERRIDC = エラー インジケータ
 *     FBRK = フットブレーキ
 *     F/B  = 前後進スイッチ
 *     BST  = ブースト
 *     PBRK = パーキングブレーキ
 */

//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C"
{
    void abort(void);
}
#endif

#include "iodefine.h"
#include "hwsetup.h"
#include "sensor_utils.h"
#include "vector_control.h"
#include "cpwm.h"
#include "interrupt_utils.h"
#include "da_handler.h"

const int intr_cycle_calc_ang_velocity = 6250; //  1 [ms]
const int intr_cycle_read_sensors = 700000;    // 28 [ms]
const int intr_cycle_control = 700000;         // 28 [ms]
const int intr_cycle_communicate = 3125;       //  1 [ms]
const int cpwm_carrier_cycle = 8000;           // 相補PWMキャリア周期
const int cpwm_deadtime = 100;                 // 相補PWMデッドタイム
const int speed_p_gain_100 = 100;              // トルクP制御ゲイン
const int speed_i_gain_100 = 100;              // トルクI制御ゲイン
const int torque_p_gain_100 = 100;             // 速度P制御ゲイン
const int torque_i_gain_100 = 100;             // 速度I制御ゲイン

int current_u;           // U相電流値; [0, 1024)
int current_v;           // V相電流値; [0, 1024)
int current_w;           // W層電流値; [0, 1024)
int current_dc;          // DC電流値; [0, 1024)
int accel;               // アクセル; [0, 1024)
int resolver;            // レゾルバ値; [0, 1024)
int resolver_err;        // レゾルバエラー
int theta;               // ロータ回転角 [deg]; [0, 360)
int ang_velocity;        // ロータ角速度 [deg/ms]; [0, +∞)
int cpwm_duty_u;         // U相PWMデューティ
int cpwm_duty_v;         // V相PWMデューティ
int cpwm_duty_w;         // W相PWMデューティ
int previous_theta;      // 前回の角速度計算割り込みで計測したろーた回転角 [deg]; [0, 360)
unsigned short da_data1; // DA データ1; [0, 4096)
unsigned short da_data2; // DA データ2; [0, 4096)
unsigned short da_data3; // DA データ3; [0, 4096)
unsigned short da_data4; // DA データ4; [0, 4096)

// MTU2 Ch.0 TGRA
void interrupt_calc_ang_velocity(void)
{
    const int delta_time = 1; // 角速度計算割り込み周期 [ms]
    int delta_theta = theta - previous_theta;

    ang_velocity = delta_theta / delta_time;
    previous_theta = theta;

    MTU20.TSR.BIT.TGFA = 0; // 割り込みフラグリセット
}

// MTU2 Ch.1 TGRA
void interrupt_read_sensors(void)
{
    get_resolver(&resolver);
    get_resolver_err_state(&resolver_err);
    get_accel(&accel);
    get_uvw_dc_current_ad(&current_u, &current_v, &current_w, &current_dc);

    current_u -= 512;
    current_v -= 512;
    current_w -= 512;

    theta = resolver_err * 720 / 1024;

    while (360 <= theta)
        theta -= 360;

    while (theta < 0)
        theta += 360;

    MTU21.TSR.BIT.TGFA = 0; // 割り込みフラグリセット
}

// MTU2 Ch.2 TGRA
void interrupt_control(void)
{
    int voltage_u;
    int voltage_v;
    int voltage_w;
    int tgr_limit = cpwm_carrier_cycle / 2;
    int tgr_margin = cpwm_deadtime;
    int tgr_upper_limit = tgr_limit - tgr_margin;
    int tgr_zero_line = tgr_limit / 2;
    int tgr_lower_limit = tgr_margin;

    da_data3 = (current_u * 4) + 2048;
    vector_control(current_u, current_v, current_w,
                   current_dc, accel, theta,
                   ang_velocity, torque_p_gain_100,
                   torque_i_gain_100, speed_p_gain_100,
                   speed_i_gain_100, &voltage_u,
                   &voltage_v, &voltage_w);

    // Voltage -> TGR
}

// CMT0
void interrupt_communicate(void)
{
    send_da_data(da_data1, da_data2, da_data3, da_data4);

    CMT0.CMCSR.BIT.CMF = 0; // 割り込みフラグリセット
}

void main(void)
{
    current_u = 0;
    current_v = 0;
    current_w = 0;
    current_dc = 0;
    accel = 0;
    resolver = 0;
    resolver_err = 0;
    theta = 0;
    ang_velocity = 0;
    cpwm_duty_u = 0;
    cpwm_duty_v = 0;
    cpwm_duty_w = 0;
    previous_theta = 0;
    da_data1 = 0;
    da_data2 = 0;
    da_data3 = 0;
    da_data4 = 0;

    // ハードウェアセットアップ
    stb_setup();
    clock_setup();
    init_cpwm_handler(cpwm_carrier_cycle, cpwm_deadtime);
    setup_interrupts(intr_cycle_calc_ang_velocity, intr_cycle_read_sensors, intr_cycle_control, intr_cycle_communicate);
    io_setup();
    setup_adconverter();

    // ベクトル制御初期化
    init_vector_controller();

    // DAコンバータ SPIインタフェース初期化
    init_da_handler();

    // MTU2, CMT0 カウント開始
    start_interrupts();

    // PWM出力開始
    start_cpwm_output();

    while (1)
        ;
}

#ifdef __cplusplus
void abort(void)
{
}
#endif
